// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
package com.mapconductor.icons

/** Common, region-neutral map symbols. Selection is always explicit. */
object CommonMapIcons {
    /** Hospital or medical facility. */
    val hospital =
        MapIconGlyph(
            id = "hospital",
            pathData = "M9 3 L15 3 L15 9 L21 9 L21 15 L15 15 L15 21 L9 21 L9 15 L3 15 L3 9 L9 9 Z",
        )
}
